name: build-rootfs
run-name: Build the base Debian rootfs
on: [push]

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: download repo
        uses: actions/checkout@v4

      - name: install deps
        run: | 
          sudo apt-get install debootstrap coreutils -y

      - name: run build
        id: run_build
        run: sudo DEBUG=1 ./build_rootfs.sh data/rootfs bookworm hostname=shimboot root_passwd=root username=user user_passwd=user
      
      - name: archive rootfs
        run: sudo tar -vcf data/rootfs.tar.gz -C data/rootfs ./

      - name: upload rootfs
        uses: actions/upload-artifact@v4
        with:
          name: rootfs_tar
          path: data/rootfs.tar.gz